### ISSUE TITLE
New APIs Tracking Issue

### ISSUE THREAD

**Issue by DevOrc** [kgpu/kgpu#4]
This is a tracking issue that will store information about the different APIs supported

- [X] **Vectors / Matrices:** 6ace19d3390dcf4087862b1cab95a22bb6a7e82a
- [X] **Shader Compliation:** 6ace19d3390dcf4087862b1cab95a22bb6a7e82a
- [x] **Mouse/Key Input:** 3e1ec6caf6d038d8fae6f27e53ad1f62c0d7494d / 22446e60e3c81ab44e2c816724122d21361c6b3e
- [x] **Window Events:** a9d4d679d5aaa46ce94576e372791283a0fb7844
- [ ] **Texture Formats:**
- [ ] **Better IO Support:**
- [ ] **Byte Utilities**

**Comment by DevOrc** [comment]
Closing this in favor of #17
